name = "RTM"
uuid = "fcc8615a-9a8c-4726-8dc2-ca4a21d574eb"
authors = ["Alexey Shiklomanov <alexey.shiklomanov@gmail.com>"]
version = "0.1.0"

[deps]
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
